
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 12 15:48:59 CDT 2014
//----------------------------------------------------

package traductor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 13;
  public static final int MENOR = 18;
  public static final int PUNTO = 10;
  public static final int DIFERENCIA = 7;
  public static final int CADENA = 24;
  public static final int SELECT = 3;
  public static final int IGUAL = 20;
  public static final int MENORIGUAL = 19;
  public static final int OR = 14;
  public static final int PAR_I = 11;
  public static final int COMO = 22;
  public static final int NOT = 15;
  public static final int PROY = 2;
  public static final int PAR_D = 12;
  public static final int CRUZ = 6;
  public static final int INTERCECTION = 4;
  public static final int TABLA = 25;
  public static final int COMA = 9;
  public static final int MAYOR = 16;
  public static final int EOF = 0;
  public static final int DIFERENTE = 21;
  public static final int MAYORIGUAL = 17;
  public static final int UNION = 5;
  public static final int NUMERO = 26;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 23;
  public static final int JOIN = 8;
}

